### ISSUE TITLE
more friendly error message for invalid type in for loops

### ISSUE THREAD

**Issue by Syuparn** [onyx-lang/onyx#109]
When an iterator value type after `in` in for loop cannot be used for iteration, a compile error below is raised.

```onyx
use core {println}
use core.list

main :: (args) => {
    l := list.make(str);
    l->push_end("foo");
    l->push_end("bar");

    for elem in l { // should be `l->as_iter()`
        println(elem);
    }
}
```

```
onyx: src/checker.c:337: check_for: Assertion `given_type' failed.
Aborted
```

As the current message does not provide much information to fix the error, messages with the error cause is more helpful.

```
// for example...
list.List cannot be used as an iterator of for loops
```

**Comment by brendanfh** [comment]
Fixed this in [ca88e2f](https://github.com/onyx-lang/onyx/commit/ca88e2f089a12e5cc7282c8329206d9f7b8b90df). Will be nightly release shortly.
