### ISSUE TITLE
Windows related time functions( ) need correction, multiple issues

### ISSUE THREAD

**Issue by the-flat-earther** [onyx-lang/onyx#114]
**My platform:** 
Processor	Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	23H2

Issue is multiple issues with time functions, they are numbered below.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1. os.time( ) -- Partial working code example, note the printf outputs
```c
    start := os.time();
    for i in 0 .. 93 {
        printf("n: {}\tFib: {}\n", i, fib(i));
    }
    stop := os.time();
    printf("\nProgram Start: {}\n", (start));
    printf("Program Stop:  {}\n", (stop));
    printf("Duration (ms):  {}\n", (stop-start));
```
Output
```
Program Start: 9519355867524
Program Stop:  9519355968072
Duration (ms):  100548
```
This ^ is off by a factor of 1,000 I believe.  The operation took about 100ms in reality (good estimate).

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2. time.now( ) -- Partial working code example, note the printf outputs
```c
    start := time.now();
    for i in 0 .. 93 {
        printf("n: {}\tFib: {}\n", i, fib(i));
    }
    stop := time.now();
    printf("\nProgram Start: {}\n", (start));
    printf("Program Stop:  {}\n", (stop));
```
Output
```
Program Start: 2271-09-08 06:34:25
Program Stop:  2271-09-08 06:35:52
```
The output ^ is clearly wrong across the board both the date, day, hour, mm, ss -- operation took only 100ms (estimate) in reality.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by brendanfh** [comment]
I believe this issue has been fixed in the newest `nightly` release, due to change in [371b62e](https://github.com/onyx-lang/onyx/commit/371b62e382459444f2d5526f593b88f64cfc4593).
