### ISSUE TITLE
Feature request: more / refactored Onyx CLI commands

### ISSUE THREAD

**Issue by josdelien** [onyx-lang/onyx#121]
Regarding the Onyx CLI, please consider the following:

- `onyx init` (instead of `onyx package init`):
Instead of first manually creating a new folder, `cd`'ing into it and then run `onyx package init` which more or less only touches `./onyx-pkg.kdl`, simply use `onyx init` from the dev projects home folder to scaffold a new Onyx project. This is inline with for example `bun init`.

- `onyx add` (instead of `onyx package add`):
See above.

- `onyx remove`:
See above.

- `onyx install` (instead of `onyx package sync`):
See above.

- This leaves room for `onyx package <sub_cmd>`: 
to deal with publishing packages, updating the (local) package indexer, etc.

- `onyx <cmd> --help`:
To provide additional help information about CLI commands. (Running this in Onyx toolchain version v0.1.9 currently yields an error message.)

- `onyx upgrade`:
To upgrade to the latest stable version from within the locally installed Onyx binary.

**Comment by brendanfh** [comment]
These new commands have been added, to a certain extent.

`onyx add`, `onyx a`, `onyx remove`, `onyx rm`, `onyx sync`, `onyx self-upgrade`, `onyx <cmd> --help` have all been added.

`onyx init` will be added later, as I have not decided if it should make a new directory or not. `bun init` actually does not make a new directory, so I'm not sure which way is better.

**Comment by brendanfh** [comment]
[297cadc](https://github.com/onyx-lang/onyx/commit/297cadce463fabf7ac68fa602b89d879e2892422) address adding `onyx init` and `onyx new`, so I'm going to close this issue.
