### ISSUE TITLE
Feature request: WebSocket Support

### ISSUE THREAD

**Issue by josdelien** [onyx-lang/onyx#123]
Please consider adding WebSocket support to the Onyx standard (core) library or as an official package like https://github.com/onyx-lang/pkg-http-client and https://github.com/onyx-lang/pkg-http-server.

A a single, specialized and native library for Websocket features is crucial for building real-time, interactive and high-performant web/networking applications, allowing for full-duplex communication channels over a single TCP connection.

**Comment by brendanfh** [comment]
This package now exists! It lives [here](https://github.com/onyx-lang/pkg-websockets). It is largely feature complete, aside from a couple of minor protocols details that will be cleaned up soon. I tested it with `echo.websockets.org` and CoinBase's Market Data API and both worked flawlessly.
