### ISSUE TITLE
www redirection issue

### ISSUE THREAD

**Issue by lorefnon** [onyx-lang/onyx#137]
The top search result for onyx language on DDG is www.onyxlang.io which redirects to itself indefinitely. 

Using https://onyxlang.io works perfectly but it looks like the redirection from www subdomain is incorrectly configured. 

![image](https://github.com/onyx-lang/onyx/assets/1449492/81ca60b3-61e5-4b0d-90d3-22a54be69ac1)

This may be confusing to new users. 

The language looks really interesting though. Thanks for open sourcing it.

**Comment by brendanfh** [comment]
Thanks for bringing this up! I will look into it. I was recently updating some hosting things so I sure I messed something up along the way.

**Comment by brendanfh** [comment]
I believe I have fixed it now!
