### ISSUE TITLE
Compiler silently dies when declaring a slice without a type

### ISSUE THREAD

**Issue by dgriffie79** [onyx-lang/onyx#150]
Declaring a slice without a type and running onyx build caused the compiler to exit silently. 

```
use core {*}

broken: []

main :: () {
    println("Hello, Onyx!")
}
```

**Comment by brendanfh** [comment]
Thanks for reporting this issue! I believe I have fixed it in [4969761](https://github.com/onyx-lang/onyx/commit/49697616a191c7462aae94993e3dc7c44f3124d4).
