### ISSUE TITLE
Error when a comment is added above a piped statement

### ISSUE THREAD

**Issue by worriedvulkan** [onyx-lang/onyx#157]
Get an error when a comment is added between any statement while using the Pipe(|>) operator. 
```
use core {*}

main :: () {
    iter.counter()
    // Comment
    |> iter.take(4)
}
```

Trying to run this code in the playground produces an error
![onyx-comments-between-piped-statements](https://github.com/user-attachments/assets/fdef1eec-a77d-4423-bc2f-d8a20c392598)

**Comment by brendanfh** [comment]
Thanks for reporting this! This is definitely an oversight and should be fixed.
