### ISSUE TITLE
No onyx binary provided in latest Release 0.1.13 ( wasmer runtime ) 

### ISSUE THREAD

**Issue by Zephr0x** [onyx-lang/onyx#161]
https://github.com/onyx-lang/onyx/releases/download/v0.1.13-beta/onyx-linux-wasmer-amd64.tar.gz

**Comment by brendanfh** [comment]
Thanks for pointing this out! Not sure what broke in the CI/CD pipeline or how it was able to publish successfully, but I will have this fixed as soon as possible.

**Comment by brendanfh** [comment]
I believe this has been fixed now. The build pipeline for Linux was using Ubuntu 20.04, which has an outdated version of GLIBC. Wasmer expected at least 2.34. I moved the pipelines to run on 24.04 and everything seems to have worked.

I updated the `onyx-linux-wasmer-amd64.tar.gz` file and installed it on my linux server and everything seems to be working now. Thanks again!
