### ISSUE TITLE
[Feature Request] Allow ! and ? as valid procedure identifier characters

### ISSUE THREAD

**Issue by clsource** [onyx-lang/onyx#168]
Release [v0.1.13-beta](https://github.com/onyx-lang/onyx/releases/tag/v0.1.13-beta) added `!` and `?` unwrap operators.

To complement such thing I think that allowing `!` and `?` in procedure identifiers can allow to mark the procedures that can be unwrapped with `!` or `?`.

```odin
my_procedure! :: () {
   // something that can panic
}
```

At the end using `!` or `?` are merely aesthethic and the procedure could still be called without them as `my_procedure()`. The lexer and parser will ignore and strip them when dealing with procedure identifiers.

**Comment by brendanfh** [comment]
I think I'm going to have to say no to this idea.

The idea of `!` and `?` is that they are unary operators that work on any type that provides an overload for them. The two types that exist in the language by default right now are `Optional(T)` (aka `? T`) and `Result(Ok, Err)`. Knowing that a procedure returns one of these types should be enough to know that you can use these operators.

You can make your own type work with them by doing
```odin
MyType :: struct {}
MyType.make :: () -> #Self { /* ... */ }

#operator! :: (mt: MyType) -> some_type {
}
```

Then you could say
```odin
MyType.make()!
```
