### ISSUE TITLE
WSL (Ubuntu 20.04) Support

### ISSUE THREAD

**Issue by magnetenstad** [onyx-lang/onyx#34]
Running WSL with Ubuntu 20.04 LTS

Installing Onyx from `sh <(curl https://get.onyxlang.io -sSfL)` outputs

```
/home/magne/.onyx/bin/onyx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/magne/.onyx/bin/onyx)
/home/magne/.onyx/bin/onyx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/magne/.onyx/bin/onyx)
/home/magne/.onyx/bin/onyx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/magne/.onyx/bin/onyx)
error: Onyx was installed, but doesn't seem to be working. Ensure this binary can be run: /home/magne/.onyx/bin/onyx
check:  installed successfully ✓
```

The same GLIBC errors arise when trying to run onyx. I've tried to
```
sudo apt update
sudo apt install libc6
```
according to [this](https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found), but nothing changed.

**Comment by magnetenstad** [comment]
Related: https://github.com/typst/typst/issues/109

**Comment by magnetenstad** [comment]
I was able to compile from source after making a small edit (#37). Now there are no problems with GLIBC. Thank you :)

**Comment by brendanfh** [comment]
Excellent! Glad that fixed it for you!
