### ISSUE TITLE
onyx/tools absent in onyx-windows-wasmer-amd64

### ISSUE THREAD

**Issue by vascoosx** [onyx-lang/onyx#38]
`pkg init` failed and the reason is because the `tools` folder is missing from https://github.com/onyx-lang/onyx/releases/download/v0.1.8-beta/onyx-windows-wasmer-amd64.zip

```
> onyx pkg init
(C:\Users\ben\onyxlang\core\runtime\platform\onyx\platform.onyx:101,29) Unable to resolve symbol 'main'. Did you mean 'map'?
 101 |     #local MAIN_FUNCTION :: main.main
                                   ^~~~
(0,0) Failed to open file C:\Users\ben\onyxlang\tools\onyx-pkg.onyx
(C:\Users\ben\onyxlang\core\runtime\platform\onyx\platform.onyx:135,5) Expected this condition to be compile time known.
 135 |     #if (typeof MAIN_FUNCTION) == #type () -> void { // An error on this line means no 'main.main' was found in your program.
           ^
(C:\Users\ben\onyxlang\core\runtime\platform\onyx\platform.onyx:100,5) Package 'main' not found in included source files.
 100 |     use main
           ^~
```

**Comment by vascoosx** [comment]
Possible workaround: clone repository and copy `scripts` directory as `tools` into `ONYX_PATH`

**Comment by brendanfh** [comment]
This was a huge oversight on my part when creating the Windows distribution. I should have installed a VM and tested it, but I didn't.

#42 addresses this and should be merged soon. But in the meantime, your workaround should work just fine.

**Comment by brendanfh** [comment]
#42 was merged so I will close this issue.
