### ISSUE TITLE
VSCode extension does not work on Windows

### ISSUE THREAD

**Issue by alexspurling** [onyx-lang/onyx#40]
The VSCode extension appears to expect a unix like path when searching for the onyx binary in ONYX_PATH. This is the error that I see when I load an Onyx project:

```
[Error - 1:22:30 PM] onyx-lsp client: couldn't create connection to server.
Launching server using command C:\Users\alexs\dev\onyx\onyx-windows-wasmer-amd64/bin/onyx failed. Error: spawn C:\Users\alexs\dev\onyx\onyx-windows-wasmer-amd64/bin/onyx ENOENT
```

There is no such directory `bin` in the Windows zip file.

I tried creating such a directory and copying the onyx.exe file into it but then I see lots of these errors:

```
[Error - 1:23:35 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 1:23:35 PM] Connection to server got closed. Server will restart.
true
[Error - 1:23:35 PM] onyx-lsp client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Either the paths of the Windows installation should match those of the Linux installation or the extension needs to be smart enough to know where to find the Onyx binary when running on Windows.

**Comment by brendanfh** [comment]
I have fixed this in the latest published version of the Onyx extension on the marketplace. The new version is `0.1.9`. It should be available soon and with any luck the LSP should work when you update the extension.

**Comment by brendanfh** [comment]
Just to double check, you can run `onyx run something.onyx` successfully, but the LSP in VS Code is failing to start?

There was an issue with the Windows build (see #33), that caused the `onyx_runtime.dll` file to be missing, which meant no program could be run. I guess a better questions is: Is there an `onyx_runtime.dll` file in your `ONYX_PATH`? If not, you should re-download the Windows version and replace your current installation. If there is, something else is the problem.
