### ISSUE TITLE
Universal newline support

### ISSUE THREAD

**Issue by magnetenstad** [onyx-lang/onyx#49]
Working with `io.read_line` and `consume_newline` for files with `\r\n` line breaks has the unexpected result that your strings end with `\r`. I would say this can be a common pitfall.

Python solves this with what they call [Universal newline support](https://peps.python.org/pep-0278/)

I can accept that keeping the `\r` is by design, but wanted to propose a suggestion in case it just hasn't been considered.

**Comment by brendanfh** [comment]
That is something I had not really run into yet, but it is a good point. I think a non-breaking code change in the standard library that adds a field to the `io.Reader` struct that controls how new lines should be processed would be the correct route. In my head it could be an optional parameter to `io.reader_make` to specify the equivalent of `rU` in Python's read modes.
