### ISSUE TITLE
Nested if expressions return the wrong result

### ISSUE THREAD

**Issue by alexspurling** [onyx-lang/onyx#77]
The following code returns an unexpected result in version (c86358ca)

```
use core {printf}

main :: () {
    printf("cmp(1, 2): {}\n", cmp(1, 2));
    printf("cmp(2, 2): {}\n", cmp(2, 2));
    printf("cmp(3, 2): {}\n", cmp(3, 2));
}

cmp :: (a: $T, b: T) -> i32 {
    return 0 if a == b else (-1 if a < b else 1);
};
```

Expected:
```
cmp(1, 2): -1
cmp(2, 2): 0
cmp(3, 2): 1
```

Actual:

```
cmp(1, 2): -1
cmp(2, 2): 0
cmp(3, 2): -1
```

**Comment by brendanfh** [comment]
After trying to fix this, I realized this is actually a *parse* error. Currently, `-1 if cond else 1` parses as `-(1 if cond else 1)`, which is very unexpected! That will be the actual fix to this issue.

You can get around it by using `(-1) if cond else 1` instead.

**Comment by brendanfh** [comment]
This has been address in #78. I added a test case to make sure it doesn't happen again. Thanks for submitting the bug!
