### ISSUE TITLE
Segmentation fault when casting

### ISSUE THREAD

**Issue by flysand7** [onyx-lang/onyx#86]
Casting integers from signed to unsigned produces segmentation fault

Repro:

```
package main;
main :: () {
    a := u32(1)<<1;
}
```

Edit: the issue seems to occur when casting to any type, not just unsigened integers

**Comment by brendanfh** [comment]
This is definitely a bug, but I will say that this is because the syntax of the cast is incorrect. The syntax you are looking for is:
```odin
package main;
main :: () {
    a := (cast(u32) 1) << 1;
    // or
    b := cast(u32, 1) << 1;
}
```

The bug is that you are trying to "call" the `u32` type, and the compiler is failing to report the error because the `u32` type doesn't have a location.
