### ISSUE TITLE
`onyx pkg` does not handle well dependent package nodes configured as git URLs in KDL

### ISSUE THREAD

**Issue by hatappo** [onyx-lang/onyx#92]
## Observations

https://github.com/hatappo/pkg-example-onyx is my example onyx package repository.

`onyx pkg add https://github.com/hatappo/pkg-example-onyx.git` produces below in `onyx-pkg.kdl`:

```kdl
// ...
dependencies {
    https://github.com/hatappo/pkg-example-onyx.git "0.3.0" git="https://github.com/hatappo/pkg-example-onyx.git" 
}
```

Then `onyx pkg sync` modify above into:

```kdl
dependencies {
    https: "0.0.0" 
}
```

## Successful Cases

`onyx pkg` command with package name of `"github.com/onyx-lang/pkg-{}"` type has no problem, such as `onyx pkg add http-server && onyx pkg sync`

## Cause

I Think there may be some improvements to the KDL parser.

## Other References

- I have tried importing packages with the documentation: https://onyxlang.io/docs/packages
- [Comments - The KDL Document Language](https://kdl.dev/#:~:text=bignum%201_000_000-,Comments,-KDL%20supports%20C)

**Comment by brendanfh** [comment]
Your fix has been merged in!
